### ISSUE TITLE
In demo_RGBD.m file, why do we rotate XYZ point cloud?

### ISSUE THREAD

**Issue by zxcv3339** [muyouhang/3DFace-Rotation#1]
Hello.
In demo_RGBD.m file, why do we rotate XYZ point cloud then do projection?
"vertex_rotate=(vertex'*RotationMatrix(0,30/180*pi,0))'; "

**Comment by muyouhang** [comment]
because this repo called "3DFace-Rotation", results :  
![20191221223730681](https://user-images.githubusercontent.com/9445862/98892560-8ef83100-24db-11eb-9752-cbc91716eb88.png)
<img width="140" alt="20191221224417605" src="https://user-images.githubusercontent.com/9445862/98892570-93bce500-24db-11eb-8952-0e9d2813d572.png">

**Comment by zxcv3339** [comment]
Thanks for your answer.
